"""End-to-end planner for one Consolidation_Opportunity.

This is what the demo calls per opportunity Tim's Phase 3 produced. It
walks every candidate SKU through qualify_candidate, scores the
surviving suppliers, drafts RFQs for the top picks, and returns a
single 'OpportunityVerdict' the UI can render.

We deliberately avoid LLM calls in the hot path. Tim can layer an LLM
'polish' on top of `justification_md` later — the audit trail and the
decision lattice itself stay deterministic.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from reasoning.gate_engine import SkuProfile
from reasoning.supplier_scorer import SupplierFeatures, SupplierScorer

from .qualify_candidate import QualificationOutcome, qualify_candidate
from .rfq import RfqSpec, draft_rfq


@dataclass
class CandidateBundle:
    """Everything we need to evaluate one candidate against the incumbent."""
    candidate_profile: SkuProfile
    candidate_name: str
    candidate_supplier_id: int
    candidate_supplier_name: str
    candidate_country: Optional[str]
    incumbent_precedents: Dict[str, bool]
    supplier_features: SupplierFeatures
    canonical_ingredient_id: int


@dataclass
class OpportunityVerdict:
    opportunity_id: int
    incumbent_name: str
    use_class: str
    jurisdictions: List[str]
    qualifications: List[QualificationOutcome] = field(default_factory=list)
    ranked_suppliers: List[dict] = field(default_factory=list)
    drafted_rfq_ids: List[int] = field(default_factory=list)
    summary_md: str = ""


def plan_opportunity(
    conn: sqlite3.Connection,
    opportunity_id: int,
    incumbent_profile: SkuProfile,
    incumbent_name: str,
    use_class: str,
    jurisdictions: List[str],
    candidates: List[CandidateBundle],
    rfq_top_n: int = 3,
) -> OpportunityVerdict:
    verdict = OpportunityVerdict(
        opportunity_id=opportunity_id,
        incumbent_name=incumbent_name,
        use_class=use_class,
        jurisdictions=jurisdictions,
    )

    # 1. Qualify each candidate independently.
    survivors: List[CandidateBundle] = []
    for cb in candidates:
        q = qualify_candidate(
            conn=conn,
            opportunity_id=opportunity_id,
            incumbent=incumbent_profile,
            candidate=cb.candidate_profile,
            incumbent_name=incumbent_name,
            candidate_name=cb.candidate_name,
            use_class=use_class,
            jurisdictions=jurisdictions,
            incumbent_precedents=cb.incumbent_precedents,
            evidence_ids=cb.supplier_features.evidence_ids,
        )
        q.candidate_supplier_name = cb.candidate_supplier_name
        verdict.qualifications.append(q)
        if q.decision in ("recommend", "defer_human_review"):
            survivors.append(cb)

    # 2. Score surviving suppliers.
    if survivors:
        scorer = SupplierScorer(conn=conn)
        # Mark compliance_pass on the SupplierFeatures based on the qualification decision.
        feats: List[SupplierFeatures] = []
        for cb in survivors:
            cb.supplier_features.compliance_pass = True
            feats.append(cb.supplier_features)
        score_tr = scorer(opportunity_id=opportunity_id, suppliers=feats)
        if score_tr.passed:
            verdict.ranked_suppliers = score_tr.result

    # 3. Draft RFQs for the top-N suppliers (always in 'draft' status).
    for ranked in verdict.ranked_suppliers[:rfq_top_n]:
        bundle = next(
            (cb for cb in survivors if cb.supplier_features.supplier_id == ranked["supplier_id"]),
            None,
        )
        if bundle is None:
            continue
        spec = RfqSpec(
            canonical_name=bundle.candidate_name,
            smiles=bundle.candidate_profile.smiles,
            unii=bundle.candidate_profile.unii,
            required_role=bundle.candidate_profile.role or "unknown",
            required_form=bundle.candidate_profile.form,
            required_grade=bundle.candidate_profile.grade,
            required_psd_bucket=bundle.candidate_profile.psd_bucket,
            target_markets=jurisdictions,
            quantity_band_kg="500-2000",
            required_certifications=["ISO 22000", "Kosher"],
            notes=f"Generated by Agnes for opportunity {opportunity_id}.",
        )
        rfq_id = draft_rfq(
            conn=conn,
            opportunity_id=opportunity_id,
            candidate_supplier_name=bundle.candidate_supplier_name,
            canonical_ingredient_id=bundle.canonical_ingredient_id,
            spec=spec,
        )
        verdict.drafted_rfq_ids.append(rfq_id)

    # 4. Compose a short summary.
    summary: List[str] = [
        f"## Opportunity #{opportunity_id} — {incumbent_name}",
        f"- use_class: `{use_class}`",
        f"- jurisdictions: {', '.join(jurisdictions)}",
        f"- candidates evaluated: {len(candidates)}",
        f"- recommend / human-review: {sum(1 for q in verdict.qualifications if q.decision in ('recommend','defer_human_review'))}",
        f"- refused: {sum(1 for q in verdict.qualifications if q.decision.startswith('refuse'))}",
        f"- top-supplier score: {(verdict.ranked_suppliers[0]['score'] if verdict.ranked_suppliers else 0):.3f}",
        f"- drafted RFQs: {len(verdict.drafted_rfq_ids)}",
        "",
        "### Per-candidate justifications",
    ]
    summary.extend(q.justification_md for q in verdict.qualifications)
    verdict.summary_md = "\n\n".join(summary)
    return verdict
