import { useState } from "react";
import { TopBar } from "@/components/layout/TopBar";
import { Sidebar, type TabKey } from "@/components/layout/Sidebar";
import { OrbHero } from "@/components/orb/OrbHero";
import { ActiveRunInline, DagGraphView } from "@/components/dag/DagGraphView";
import { OpportunitiesView } from "@/components/views/OpportunitiesView";
import { IngredientsView } from "@/components/views/IngredientsView";
import { ComplianceView } from "@/components/views/ComplianceView";
import { ProposalsView } from "@/components/views/ProposalsView";
import { PipelineRunsView } from "@/components/views/PipelineRunsView";
import { SuppliersView } from "@/components/views/SuppliersView";
import { AlertsView } from "@/components/views/AlertsView";
import { RegulatoryAlertsView } from "@/components/views/RegulatoryAlertsView";
import { TradeRoutesView } from "@/components/views/TradeRoutesView";
import { useApiHealth } from "@/hooks/useApiHealth";
import { useAgnesStore } from "@/store/agnesStore";

const TAB_TITLES: Record<TabKey, { title: string; subtitle: string }> = {
  agnes: { title: "Talk to Agnes", subtitle: "Voice-driven procurement intelligence for your CPG bill of materials." },
  opportunities: { title: "Consolidation Opportunities", subtitle: "Ingredients sourced from too many suppliers — ranked by AI score." },
  ingredients: { title: "Ingredient Catalog", subtitle: "Enriched ingredient data from PubChem, DSLD and Molport." },
  compliance: { title: "Compliance Matrix", subtitle: "Certification coverage across products and companies." },
  proposals: { title: "AI Proposals", subtitle: "Procurement proposals generated by Agnes." },
  runs: { title: "Pipeline Runs", subtitle: "History and live execution of Agnes' agent pipelines." },
  suppliers: { title: "Supplier Scoring", subtitle: "Rank suppliers by price, lead time, and quality — adjustable weights." },
  alerts: { title: "Price Alerts", subtitle: "Market price changes detected by Agnes — drops are sourcing opportunities, increases are cost risks." },
  regulatory: { title: "Regulatory Alerts", subtitle: "FDA IID changes affecting portfolio ingredients — proactive compliance risk monitoring." },
  routes: { title: "Trade Routes", subtitle: "Indicative freight lanes by origin, mode, lead time, and cost — sorted by landed cost index." },
};

const Index = () => {
  const [tab, setTab] = useState<TabKey>("agnes");
  const { apiOnline } = useApiHealth();
  const activeRunId = useAgnesStore((s) => s.activeRunId);
  const activeGraph = useAgnesStore((s) => s.activeGraph);

  const meta = TAB_TITLES[tab];

  return (
    <div className="flex flex-col h-screen bg-background">
      <TopBar />

      {!apiOnline && (
        <div className="bg-status-skipped/10 border-b border-status-skipped/20 px-5 py-1.5 text-[12px] text-status-skipped flex items-center gap-2">
          <span className="size-1.5 rounded-full bg-status-skipped animate-status-pulse" />
          Agnes API offline at <code className="font-mono">localhost:8001</code> — running on seeded demo data. Toggle <strong>Live data</strong> in the top right when your FastAPI server is reachable.
        </div>
      )}

      <div className="flex flex-1 min-h-0">
        <Sidebar active={tab} onSelect={setTab} />

        <main className="flex-1 min-w-0 overflow-auto scrollbar-thin">
          <div className="px-8 pt-7 pb-2">
            <h1 className="text-[22px] font-semibold tracking-tight text-foreground">{meta.title}</h1>
            <p className="text-[13px] text-muted-foreground mt-0.5 max-w-2xl">{meta.subtitle}</p>
          </div>

          <div className="px-8 pb-10 pt-4">
            {tab === "alerts" ? <AlertsView />
              : tab === "suppliers" ? <SuppliersView />
              : tab === "agnes" ? (
              <div className="flex flex-col gap-6 max-w-4xl mx-auto">
                {/* Live DAG — shown at top when a run is active */}
                {activeRunId && activeGraph && (
                  <div>
                    <p className="text-[11px] uppercase tracking-wider text-muted-foreground font-semibold mb-2">
                      Live Pipeline Execution
                    </p>
                    <DagGraphView graph={activeGraph} />
                  </div>
                )}

                {/* Orb + controls */}
                <div className="flex flex-col items-center">
                  <OrbHero
                    size={activeRunId ? 180 : 240}
                    onNavigateTo={setTab}
                  />
                  {!activeRunId && (
                    <div className="mt-6 w-full max-w-sm space-y-2">
                      <div className="rounded-lg border border-dashed border-border p-3 text-[12px] text-muted-foreground space-y-1">
                        <p className="font-medium text-foreground/80 text-[12px]">Try asking</p>
                        <p>"Find consolidation opportunities for Vitamin C"</p>
                        <p>"What's our best Magnesium supplier?"</p>
                        <p>"Audit prices on Omega-3 ingredients"</p>
                      </div>
                    </div>
                  )}
                </div>

                {/* "How Agnes thinks" — only shown when idle */}
                {!activeRunId && (
                  <div className="rounded-xl border border-border bg-surface-subtle/40 p-8">
                    <p className="text-[13px] font-medium text-foreground mb-1">How Agnes thinks</p>
                    <p className="text-[12.5px] text-muted-foreground leading-relaxed mb-4">
                      When you speak to Agnes, your transcript is routed to one of 5 AI pipelines. Each pipeline is a DAG of Claude agents and deterministic tools, executed in topological layers. You'll see the live graph render here in real time.
                    </p>
                    <ul className="text-[12.5px] space-y-1.5 text-foreground/85">
                      <li>• <span className="font-mono">proactive_consolidation</span> — find redundant suppliers</li>
                      <li>• <span className="font-mono">supplier_fallout</span> — react to supplier disruption</li>
                      <li>• <span className="font-mono">price_audit</span> — flag pricing outliers</li>
                      <li>• <span className="font-mono">substitution_discovery</span> — search Molport / PubChem</li>
                      <li>• <span className="font-mono">new_ingredient_research</span> — regulatory sweep</li>
                    </ul>
                  </div>
                )}
              </div>
            ) : tab === "opportunities" ? <OpportunitiesView />
              : tab === "ingredients" ? <IngredientsView />
              : tab === "compliance" ? <ComplianceView />
              : tab === "proposals" ? <ProposalsView />
              : tab === "runs" ? <PipelineRunsView />
              : tab === "regulatory" ? <RegulatoryAlertsView />
              : tab === "routes" ? <TradeRoutesView />
              : <SuppliersView />
            }
          </div>
        </main>
      </div>
    </div>
  );
};

export default Index;
